name: Build and Test

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

env:
  psql_url: ${{ secrets.URL }} 
  psql_username: ${{ secrets.USERNAME }} 
  psql_password: ${{ secrets.PASSWORD }} 

jobs:
  runchecks:
    name: "Checkout Code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "validate - validate the changelog"
        uses: liquibase-github-actions/validate@v4.21.1
        with:
          changeLogFile: "changelogs/example-changelog.sql"
          url: 'jdbc:postgresql://ep-icy-dream-444207.us-east-2.aws.neon.tech:5432/neondb'
          driver: 'org.postgresql.Driver'
          username: 'b.sreshtant'
          password: 'vqjz7CBk1YGi'

      - name: "Status - Output the changesets that will be deployed"
        uses: liquibase-github-actions/status@v4.21.1
        with:
          changeLogFile: "changelogs/example-changelog.sql"
          url: 'jdbc:postgresql://ep-icy-dream-444207.us-east-2.aws.neon.tech:5432/neondb'
          driver: 'org.postgresql.Driver'
          username: 'b.sreshtant'
          password: 'vqjz7CBk1YGi'
          verbose: True

      - name: "Checks run - Check the changelog or database for issues"
        uses: liquibase-github-actions/checks-run@v4.21.1
        with:
          changeLogFile: "changelogs/example-changelog.sql"
          url: 'jdbc:postgresql://ep-icy-dream-444207.us-east-2.aws.neon.tech:5432/neondb'
          driver: 'org.postgresql.Driver'
          username: 'b.sreshtant'
          password: 'vqjz7CBk1YGi'

      - name: "Update - Update the changes"
        uses: liquibase-github-actions/update@v4.21.1
        with:
          changeLogFile: "changelogs/example-changelog.sql"
          url: 'jdbc:postgresql://ep-icy-dream-444207.us-east-2.aws.neon.tech:5432/neondb'
          driver: 'org.postgresql.Driver'
          username: 'b.sreshtant'
          password: 'vqjz7CBk1YGi'
        if: github.event_name == 'push' 