name: Build and Test

on:
  push:
    branches: [ development, staging, master ]
  pull_request:
    branches: [ development, staging, master ]

env:
  dev_db: 'devDB'
  psql_url: 'jdbc:postgresql://ep-icy-dream-444207.us-east-2.aws.neon.tech:5432/'
  psql_username: 'b.sreshtant'
  psql_password: 'vqjz7CBk1YGi'
  psql_driver:  'org.postgresql.Driver'

jobs:
  runchecks:
    name: "POC CI/CD Liquibase"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Generate Changelogs"
        uses: liquibase-github-actions/generate-changelog@v4.23.0
        with:
          changeLogFile: "changelogs/example-changelog.sql"
          url: '${{ env.psql_url }}${{ env.dev_db}}'
          driver: '${{ env.psql_driver }}'
          username: '${{ env.psql_username }}'
          password: '${{ env.psql_password }}'
