name: Build and Test

on: [push, pull_request]

jobs:
  runchecks:
    name: "Checkout Code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: liquibase-github-actions/validate@v4.21.1
        with:
          changeLogFile: "changelogs/example-changelog.sql"
          url: 'jdbc:postgresql://ep-icy-dream-444207.us-east-2.aws.neon.tech:5432/neondb'
          driver: 'org.postgresql.Driver'
          username: 'b.sreshtant'
          password: 'vqjz7CBk1YGi'

      - uses: liquibase-github-actions/checks-run@v4.21.1
        with:
          changeLogFile: "changelogs/example-changelog.sql"
          url: 'jdbc:postgresql://ep-icy-dream-444207.us-east-2.aws.neon.tech:5432/neondb'
          driver: 'org.postgresql.Driver'
          username: 'b.sreshtant'
          password: 'vqjz7CBk1YGi'

      - uses: liquibase-github-actions/status@v4.21.1
        with:
          changeLogFile: "changelogs/example-changelog.sql"
          url: 'jdbc:postgresql://ep-icy-dream-444207.us-east-2.aws.neon.tech:5432/neondb'
          driver: 'org.postgresql.Driver'
          username: 'b.sreshtant'
          password: 'vqjz7CBk1YGi'
          verbose: True

      - uses: liquibase-github-actions/update@v4.21.1
        with:
          changeLogFile: "changelogs/example-changelog.sql"
          url: 'jdbc:postgresql://ep-icy-dream-444207.us-east-2.aws.neon.tech:5432/neondb'
          driver: 'org.postgresql.Driver'
          username: 'b.sreshtant'
          password: 'vqjz7CBk1YGi'