name: Build and Test

on:
  push:
    branches: [ development, staging, master ]


env:
  dev_db: 'devDB'
  qa_db: 'qaDB'
  prod_DB: 'prodDB'
  psql_driver:  'org.postgresql.Driver'
  
jobs:
  runchecks:
    name: "Preprocessing"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Console"
        run: echo "$GITHUB_REF"

  dev-data-migration:
      if: github.ref == 'refs/heads/development' && github.event_name == 'push'
      name: "DEV Data Migration"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: "Update - Update the changes"
          uses: liquibase-github-actions/update@v4.21.1
          with:
            changeLogFile: "root.xml"
            url: '${{ secrets.url }}${{ env.dev_db }}'
            driver: '${{ env.psql_driver }}'
            username: '${{ secrets.username }}'
            password: '${{ secrets.password }}'
            
  qa-data-migration:
      if: github.ref == 'refs/heads/staging' && github.event_name == 'push'
      name: "QA Data Migration"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: "Update - Update the changes"
          uses: liquibase-github-actions/update@v4.21.1
          with:
            changeLogFile: "root.xml"
            url: '${{ secrets.url }}${{ env.qa_db }}'
            driver: '${{ env.psql_driver }}'
            username: '${{ secrets.username }}'
            password: '${{ secrets.password }}'
            
  prod-data-migration:
      if: github.ref == 'refs/heads/master' && github.event_name == 'push'
      name: "PROD Data Migration"
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v3
        - name: "Update - Update the changes"
          uses: liquibase-github-actions/update@v4.21.1
          with:
            changeLogFile: "root.xml"
            url: '${{ secrets.url }}${{ env.prod_DB }}'
            driver: '${{ env.psql_driver }}'
            username: '${{ secrets.username }}'
            password: '${{ secrets.password }}'
  
