name: Build and Test

on: [push, pull_request]

jobs:
  runchecks:
    name: "Checkout Code"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: liquibase/liquibase-github-action@v5
        with:
          operation: "status"
          changeLogFile: "changelogs/example-changelog.sql"
          url: 'jdbc:postgresql://ep-icy-dream-444207.us-east-2.aws.neon.tech:5432/neondb'
          username: 'b.sreshtant'
          password: 'vqjz7CBk1YGi'